### ISSUE TITLE
Plugin could not be registered at 'html-webpack-plugin-alter-asset-tags'. Hook was not found.

### ISSUE THREAD

**Issue by santhoshsvkmm** [MwumLi/html-webpack-alter-asset-plugin#1]

**Comment by MwumLi** [comment]
'html-webpack-plugin-alter-asset-tags' is here: https://github.com/jantimon/html-webpack-plugin/tree/v3.2.0#async  
This plugin  only uses hook [html-webpack-plugin-before-html-generation](https://github.com/jantimon/html-webpack-plugin/tree/v3.2.0#async)
